// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdf8FuwTcKPznKbblMZHek14M53T58o4E',
    appId: '1:394831104723:web:0269ff97edbb66cd41a226',
    messagingSenderId: '394831104723',
    projectId: 'alugafacil-2b5e8',
    authDomain: 'alugafacil-2b5e8.firebaseapp.com',
    storageBucket: 'alugafacil-2b5e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6tjikBjmsfnX3g1-VJuTu10UR81OArYE',
    appId: '1:394831104723:android:f913aa5dcf692d3641a226',
    messagingSenderId: '394831104723',
    projectId: 'alugafacil-2b5e8',
    storageBucket: 'alugafacil-2b5e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYc7P9CPyYQWbl8_yyiin6_SETe05yfHM',
    appId: '1:394831104723:ios:fc23ff9e2204e40941a226',
    messagingSenderId: '394831104723',
    projectId: 'alugafacil-2b5e8',
    storageBucket: 'alugafacil-2b5e8.firebasestorage.app',
    iosBundleId: 'com.reiffer.alugafacil.alugaFacil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYc7P9CPyYQWbl8_yyiin6_SETe05yfHM',
    appId: '1:394831104723:ios:fc23ff9e2204e40941a226',
    messagingSenderId: '394831104723',
    projectId: 'alugafacil-2b5e8',
    storageBucket: 'alugafacil-2b5e8.firebasestorage.app',
    iosBundleId: 'com.reiffer.alugafacil.alugaFacil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdf8FuwTcKPznKbblMZHek14M53T58o4E',
    appId: '1:394831104723:web:834ee30cb07b7f0741a226',
    messagingSenderId: '394831104723',
    projectId: 'alugafacil-2b5e8',
    authDomain: 'alugafacil-2b5e8.firebaseapp.com',
    storageBucket: 'alugafacil-2b5e8.firebasestorage.app',
  );
}